### ISSUE TITLE
frp下载，更好的实现方式

### ISSUE THREAD

**Issue by whx1024** [Harry-zklcdc/go-proxy-bingai-ga#1]
这样可获取最新版本frp
  DL_URL=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | grep linux_amd64 | grep browser_download_url | cut -d '"' -f 4)
  wget -q ${DL_URL} -O frp.tar.gz
  tar -xzf frp.tar.gz

**Comment by Harry-zklcdc** [comment]
之后更新，其实就是懒，不然可以用另外的更优雅的方式实现的（）

**Comment by Harry-zklcdc** [comment]
已采纳 8d79d1fc8a1692d7b7a393b026d3acbf0cf0a42e
